pipeline {
    environment {
        repository = "1w2k/code-odyssesy"
        DOCKERHUB_CREDENTIALS = credentials('docker_credentials')
        dockerImage = ''
        TARGET_HOST = "ubuntu@152.67.210.191"
    }
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // 코드 체크아웃
                    checkout scm
                }
            }
        }

        stage('Build FE Image') {
            steps {
                script {
                    dockerImage = docker.build("${repository}:FE_${BUILD_NUMBER}", "-f FrontEnd/Dockerfile ./FrontEnd")
                }
            }
        }

        stage('Login') {
            steps {
                script {
                    sh "echo \${DOCKERHUB_CREDENTIALS_PSW} | docker login -u \${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                }
            }
        }

        stage('Push FE Image to Docker Hub') {
            steps {
                script {
                    sh "docker push \${repository}:FE_\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean FE Image') {
            steps {
                script {
                    sh "docker rmi \${repository}:FE_\${BUILD_NUMBER}"
                }
            }
        }

        stage('Print') {
            steps {
                script {
                    // 변경된 브랜치와 머지 대상 브랜치 출력
                    // 현재 빌드 중인 브랜치명 확인
                    def currentBranch = env.BRANCH_NAME
                    echo "Merge Target Branch : \${CHANGE_TARGET}"
                    echo "Current Branch: \${currentBranch}"

                    echo "프론트엔드입니다."

                    // 여기에 빌드 스텝 추가
                }
            }
        }

        #이 부분을 지난번에 추가로 작성합니다.
        #GarbageCollecTESTSERV 는 현재 돌아가고 있는 서버의 컨테이너와 자원을 정리합니다.
        stage("GarbageCollecTESTSERV") {
            steps {
                sshPublisher(
                    continueOnError: true, failOnError: false,
                    publishers: [
                        sshPublisherDesc(
                            configName: "ORACLE_SERVER_1",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "docker kill \$(docker ps | grep mize | tr ' ' '\t' | cut -f1)"),
                                sshTransfer(execCommand: "docker system prune -af")
                            ]
                        )
                    ]
                )
            }
        }
        #여기에서는 배포를 실행합니다.
        stage("TestDeploy") {
            steps {
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "ORACLE_SERVER_1",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "docker pull " + repository +":FE$BUILD_NUMBER"),
                                sshTransfer(execCommand: "docker run -d -p 80:80 " + repository +":FE$BUILD_NUMBER")
                            ]
                        )
                    ]
                )
            }
        }
    }
    
    
}
