export const sprintImage: Record<string, string> = {
  STRING: '/images/code_odyssey/sprint/lion.svg',
  MATH: '/images/code_odyssey/sprint/goat.svg',
  'DATA STRUCTURE': '/images/code_odyssey/sprint/bottle.svg',
  'BRUTE FORCE': '/images/code_odyssey/sprint/bull.svg',
  TREE: '/images/code_odyssey/sprint/scorpion.svg',
  GRAPH: '/images/code_odyssey/sprint/sheep.svg',
  'AD HOC': '/images/code_odyssey/sprint/crab.svg',
  DP: '/images/code_odyssey/sprint/virgin.svg',
  'SHORTEST PATH': '/images/code_odyssey/sprint/fish.svg',
  'BINARY SEARCH': '/images/code_odyssey/sprint/libra.svg',
  GREEDY: '/images/code_odyssey/sprint/archer.svg',
  SIMULATION: '/images/code_odyssey/sprint/twins.svg',
  'STRING FIN': '/images/code_odyssey/sprint/lion_fin.svg',
  'MATH FIN': '/images/code_odyssey/sprint/goat_fin.svg',
  'DATA STRUCTURE FIN': '/images/code_odyssey/sprint/bottle_fin.svg',
  'BRUTE FORCE FIN': '/images/code_odyssey/sprint/bull_fin.svg',
  'TREE FIN': '/images/code_odyssey/sprint/scorpion_fin.svg',
  'GRAPH FIN': '/images/code_odyssey/sprint/sheep_fin.svg',
  'AD HOC FIN': '/images/code_odyssey/sprint/crab_fin.svg',
  'DP FIN': '/images/code_odyssey/sprint/virgin_fin.svg',
  'SHORTEST PATH FIN': '/images/code_odyssey/sprint/fish_fin.svg',
  'BINARY SEARCH FIN': '/images/code_odyssey/sprint/libra_fin.svg',
  'GREEDY FIN': '/images/code_odyssey/sprint/archer_fin.svg',
  'SIMULATION FIN': '/images/code_odyssey/sprint/twins_fin.svg',
};

export const sprintName: Record<string, string> = {
  STRING: '사자자리',
  MATH: '염소자리',
  'DATA STRUCTURE': '물병자리',
  'BRUTE FORCE': '황소자리',
  TREE: '전갈자리',
  GRAPH: '양자리',
  'AD HOC': '게자리',
  DP: '처녀자리',
  'SHORTEST PATH': '물고기자리',
  'BINARY SEARCH': '천칭자리',
  GREEDY: '궁수자리',
  SIMULATION: '쌍둥이자리',
};

export const sprintContent: Record<string, string> = {
  STRING: '출제할 수 있는 유형 중 가장 어려운 문제를 정복해보세요',
  MATH: '염소를 따라 신비한 수학의 원리를 탐구하세요',
  'DATA STRUCTURE': '물병에 자료를 효율적으로 담는 법을 연구해보세요',
  'BRUTE FORCE': '무식한 황소처럼 모든 경우를 탐색해보세요',
  TREE: '전갈 다리처럼 복잡하게 뻗어나가는 트리를 탐색하세요',
  GRAPH: '양털처럼 복잡하게 얽힌 그래프를 탐험하세요',
  'AD HOC': '앞이 아닌, 옆으로 걷는 게처럼 다르게 생각해야 풀려요',
  DP: '테이블에 경우의 수를 정리하는 방법을 배워보세요',
  'SHORTEST PATH': '귀소하는 연어에게 최단 경로를 알려주세요',
  'BINARY SEARCH': '효율적으로 범위를 나누어 탐색하는 법을 배우세요',
  GREEDY: '욕심쟁이 궁수에게 사냥감을 쓸어담는 법을 배우세요',
  SIMULATION: '현실 속 문제를 코드로 복제하는 연습을 해보세요',
};
