version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  common-redis:                        # 서비스명
    container_name: common-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: 1w2k/common-redis
    ports:
      - "6379:6379"
  common-server:
    container_name: common-server
    build: .
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - common-redis
    image: 1w2k/common-server
    environment:
      - DB_URL=${env.RDB_COMMON_URL}
      - DB_USER=${env.RDB_USER}
      - DB_PASSWORD=${env.RDB_PASSWORD}
      - KAKAO_OAUTH_SECRET=${env.KAKAO_OAUTH_SECRET}
      - KAKAO_OAUTH_ID=${env.KAKAO_OAUTH_ID}
      - NAVER_OAUTH_SECRET=${env.NAVER_OAUTH_SECRET}
      - NAVER_OAUTH_ID=${env.NAVER_OAUTH_ID}
      - GOOGLE_OAUTH_SECRET=${env.GOOGLE_OAUTH_SECRET}
      - GOOGLE_OAUTH_ID=${env.GOOGLE_OAUTH_ID}
      - JWT_ACCESS=${env.JWT_ACCESS}
      - JWT_REFRESH=${env.JWT_REFRESH}
      - FRONT_SERVER=${env.FRONT_SERVER}
      - DISCOVERY_SERVER=${env.DISCOVERY_SERVER}
    ports:
      - "8777:8777"
