version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  common-redis:                        # 서비스명
    container_name: common-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: 1w2k/common-redis
    ports:
      - "6379:6379"
  common-db:
    container_name: common-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: 1w2k/common-db
    environment:
      - MARIADB_DATABASE=S10P12C205
      - MARIADB_ROOT_PASSWORD=${RDB_ROOT_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)