version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  common-redis:                        # 서비스명
    container_name: chatting-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: 1w2k/chatting-redis
    ports:
      - "6379:6379"
    networks:
      - chatting-network
  common-server:
    container_name: chatting-server
    build: .
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - chatting-redis
    image: 1w2k/chatting-server
    ports:
      - "8080:8080"
    restart: always # depends on은 실행 순서만 컨트롤 할뿐,
    # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정
    networks:
      - chatting-network
networks:
  common-network:
    driver: bridge