server:
  port: 8761


spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
