# Generated by Django 4.2.9 on 2024-02-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemdata',
            old_name='types',
            new_name='category',
        ),
    ]
