# Generated by Django 5.0.1 on 2024-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='inputSample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='outputSample',
            field=models.TextField(blank=True, null=True),
        ),
    ]
