# Generated by Django 4.2.9 on 2024-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='link',
            field=models.TextField(),
        ),
    ]
